version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      
  build:
    commands:
      - echo "Starting Flask Application Build"
      
  post_build:
    commands:
      - echo "Build complete, moving to deployment phase"

artifacts:
  files:
    - '**/*'
